import { Item } from './item.model';
import { ITEM_ID } from './item.constants';

export const ItemData: Item[] = [
  // === 種子類 ===
  {
    id: ITEM_ID.WHEAT_SEED,
    name: '小麥種子',
    icon: '🌾',
    type: 'seed',
    price: 1,
    sellPrice: 0,
    displayOrder: 0,
    description: '基礎作物種子，成長快速。',
  },
  {
    id: ITEM_ID.CORN_SEED,
    name: '玉米種子',
    icon: '🌽',
    type: 'seed',
    price: 5,
    sellPrice: 0,
    displayOrder: 1,
    description: '營養豐富的作物種子。',
  },
  {
    id: ITEM_ID.CARROT_SEED,
    name: '胡蘿蔔種子',
    icon: '🥕',
    type: 'seed',
    price: 8,
    sellPrice: 0,
    displayOrder: 2,
    description: '根莖類蔬菜種子。',
  },
  {
    id: ITEM_ID.APPLE_SEED,
    name: '蘋果種子',
    icon: '🍎',
    type: 'seed',
    price: 15,
    sellPrice: 0,
    displayOrder: 3,
    description: '水果樹種子，需要更長時間成長。',
  },
  {
    id: ITEM_ID.STRAWBERRY_SEED,
    name: '草莓種子',
    icon: '🍓',
    type: 'seed',
    price: 20,
    sellPrice: 0,
    displayOrder: 4,
    description: '甜美的漿果種子。',
  },
  {
    id: ITEM_ID.TOMATO_SEED,
    name: '番茄種子',
    icon: '🍅',
    type: 'seed',
    price: 12,
    sellPrice: 0,
    displayOrder: 5,
    description: '多用途蔬菜種子。',
  },
  {
    id: ITEM_ID.POTATO_SEED,
    name: '馬鈴薯種子',
    icon: '🥔',
    type: 'seed',
    price: 6,
    sellPrice: 0,
    displayOrder: 6,
    description: '澱粉類作物種子。',
  },

  // === 農作物 ===
  {
    id: ITEM_ID.WHEAT,
    name: '小麥',
    icon: '🌾',
    type: 'crop',
    price: 0,
    sellPrice: 2,
    displayOrder: 0,
    description: '基礎農作物，可用於製作麵粉。',
  },
  {
    id: ITEM_ID.CORN,
    name: '玉米',
    icon: '🌽',
    type: 'crop',
    price: 0,
    sellPrice: 10,
    displayOrder: 1,
    description: '營養豐富的穀物。',
  },
  {
    id: ITEM_ID.CARROT,
    name: '胡蘿蔔',
    icon: '🥕',
    type: 'crop',
    price: 0,
    sellPrice: 15,
    displayOrder: 2,
    description: '富含維生素的根莖類蔬菜。',
  },
  {
    id: ITEM_ID.APPLE,
    name: '蘋果',
    icon: '🍎',
    type: 'crop',
    price: 0,
    sellPrice: 25,
    displayOrder: 3,
    description: '香甜的水果。',
  },
  {
    id: ITEM_ID.STRAWBERRY,
    name: '草莓',
    icon: '🍓',
    type: 'crop',
    price: 0,
    sellPrice: 30,
    displayOrder: 4,
    description: '鮮美的漿果。',
  },
  {
    id: ITEM_ID.TOMATO,
    name: '番茄',
    icon: '🍅',
    type: 'crop',
    price: 0,
    sellPrice: 18,
    displayOrder: 5,
    description: '多用途蔬菜，可製作各種料理。',
  },
  {
    id: ITEM_ID.POTATO,
    name: '馬鈴薯',
    icon: '🥔',
    type: 'crop',
    price: 0,
    sellPrice: 12,
    displayOrder: 6,
    description: '澱粉豐富的塊莖作物。',
  },

  // === 動物產品 ===
  {
    id: ITEM_ID.EGG,
    name: '雞蛋',
    icon: '🥚',
    type: 'produce',
    price: 0,
    sellPrice: 25,
    displayOrder: 0,
    description: '新鮮雞蛋，可用於烹飪。',
  },
  {
    id: ITEM_ID.MILK,
    name: '牛奶',
    icon: '🥛',
    type: 'produce',
    price: 0,
    sellPrice: 50,
    displayOrder: 1,
    description: '新鮮牛奶，營養豐富。',
  },
  {
    id: ITEM_ID.WOOL,
    name: '羊毛',
    icon: '🧶',
    type: 'produce',
    price: 0,
    sellPrice: 60,
    displayOrder: 2,
    description: '柔軟的羊毛，可用於製作衣物。',
  },
  {
    id: ITEM_ID.HONEY,
    name: '蜂蜜',
    icon: '🍯',
    type: 'produce',
    price: 0,
    sellPrice: 80,
    displayOrder: 3,
    description: '甜美的天然蜂蜜。',
  },

  // === 加工食品 ===
  {
    id: ITEM_ID.TOAST,
    name: '吐司',
    icon: '🍞',
    type: 'processed',
    price: 0,
    sellPrice: 5,
    displayOrder: 0,
    description: '由小麥加工而成的基礎食材。',
  },
  {
    id: ITEM_ID.CHEESE,
    name: '起司',
    icon: '🧀',
    type: 'processed',
    price: 0,
    sellPrice: 120,
    displayOrder: 1,
    description: '由牛奶發酵製成的美味起司。',
  },
  {
    id: ITEM_ID.BUTTER,
    name: '奶油',
    icon: '🧈',
    type: 'processed',
    price: 0,
    sellPrice: 80,
    displayOrder: 2,
    description: '由牛奶提煉而成的香濃奶油。',
  },
  {
    id: ITEM_ID.BREAD,
    name: '麵包',
    icon: '🍞',
    type: 'processed',
    price: 0,
    sellPrice: 15,
    displayOrder: 3,
    description: '由麵粉烘焙而成的基礎食品。',
  },
  {
    id: ITEM_ID.CAKE,
    name: '蛋糕',
    icon: '🍰',
    type: 'processed',
    price: 0,
    sellPrice: 200,
    displayOrder: 4,
    description: '精緻的甜點，需要多種食材製作。',
  },
  {
    id: ITEM_ID.JAM,
    name: '果醬',
    icon: '🍓',
    type: 'processed',
    price: 0,
    sellPrice: 60,
    displayOrder: 5,
    description: '由水果熬煮而成的甜美果醬。',
  },
  {
    id: ITEM_ID.PIZZA,
    name: '披薩',
    icon: '🍕',
    type: 'processed',
    price: 0,
    sellPrice: 180,
    displayOrder: 6,
    description: '美味的義式披薩。',
  },
  {
    id: ITEM_ID.YOGURT,
    name: '優格',
    icon: '🥛',
    type: 'processed',
    price: 0,
    sellPrice: 70,
    displayOrder: 7,
    description: '由牛奶發酵製成的健康食品。',
  },
  {
    id: ITEM_ID.FRIES,
    name: '薯條',
    icon: '🍟',
    type: 'processed',
    price: 0,
    sellPrice: 35,
    displayOrder: 8,
    description: '由馬鈴薯製作的酥脆薯條。',
  },
  {
    id: ITEM_ID.KETCHUP,
    name: '番茄醬',
    icon: '🍅',
    type: 'processed',
    price: 0,
    sellPrice: 25,
    displayOrder: 9,
    description: '由番茄製作的萬用調味料。',
  },
];
